- name: nomad server inst
  hosts: nomad_worker
  vars:
    - dist_dir: "../../D-1-6/distrib/"
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"
  tags:
    - consul

  tasks:

    - name: copy nomand && consul binary to nodes
      copy:
        src: "{{ dist_dir }}{{ item }}"
        dest: "/usr/local/sbin"
        owner: root
        group: root
        mode: "o=rwx,g=rx,o=r"
      with_items:
        - nomad
        - consul

    - name: prepare consul directory
      file:
        path: /etc/consul.d/client
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=r"
        recurse: true

    - name: copy config to server
      copy:
        src: "./config/consul_cl_01/config.json"
        dest: "/etc/consul.d/client/"
        decrypt: true
        owner: root
        group: root
        mode: "u=rwx,g=rw,o=r"
      when: inventory_hostname in groups["worker01"]


    - name: copy config to server
      copy:
        src: "./config/consul_cl_02/config.json"
        dest: "/etc/consul.d/client/"
        decrypt: true
        owner: root
        group: root
        mode: "u=rwx,g=rw,o=r"
      when: inventory_hostname in groups["worker02"]

    - name: copy startup script to server
      copy:
        src: "./config/consul_cl_01/consul.service"
        dest: "/etc/systemd/system/"
        owner: root
        group: root
        mode: "u=rwx,g=rwx,o=r"

    - name: start consul server
      systemd:
        name: consul
        state: started
        enabled: true

- name: nomad client post consul config
  hosts: nomad_worker
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"
  tags:
    - nomad_conf

  tasks:

    - name: prepare nomad work directory
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "u=rwx,g=rx,o=r"
      with_items:
        - "/etc/nomad.d"
        - "/opt/nomad"

    - name: copy config to server
      copy:
        src: "./config/consul_cl_01/{{ item }}"
        dest: "/etc/nomad.d/"
        owner: root
        group: root
        mode: "0750"
      with_items:
        - nomad.hcl
        - client.hcl
      when: inventory_hostname in groups["worker01"]

    - name: copy config to server
      copy:
        src: "./config/consul_cl_02/{{ item }}"
        dest: "/etc/nomad.d/"
        owner: root
        group: root
        mode: "0750"
      with_items:
        - nomad.hcl
        - client.hcl
      when: inventory_hostname in groups["worker02"]

    - name: copy nomad startup script to server
      copy:
        src: "./config/consul_srv/nomad.service"
        dest: "/etc/systemd/system/"
        owner: root
        group: root
        mode: "u=rw,g=rw,o=r"

    - name: start nomad server
      systemd:
        name: nomad
        state: restarted
        enabled: true

- name: ishop
  hosts: nomad_worker
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"
  tags:
    - ishop

  tasks:

    - name: copy netman
      copy:
        src: "./config/netman.sh"
        dest: "/usr/bin/"
        owner: root
        group: root
        mode: "u=rwx,g=rwx,o=rx"
