- name: nomad
  hosts: nomad
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: copy nomad binary to VN
      copy:
        src: "../distrib/nomad"
        dest: "/usr/local/sbin"
        owner: root
        group: root
        mode: o=rwx,g=rx,o=r