- name: install docker && nomad
  hosts: nomad
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: install nedeed pachage
      package:
        name:
          - ca-certificates
          - curl
          - wget
          - apt-transport-https
          - software-properties-common
          - gpg
          - coreutils
        state: present
        update_cache: true

    - name: create distrib directory
      file:
        path: /usr/distrib
        state: directory
        owner: root
        group: root
        mode: "0775"

    - name: add docker repo gpg key
      shell:
        cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"

    - name: add docker repo
      shell:
        cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null'

    - name: update cache && install docker
      package:
        name: docker-ce
        state: present
        update_cache: true

    - name: run docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: pull nomad gpg key
      shell:
        cmd: "wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg"
        chdir: "/usr/distrib"

    - name: add hashicorp repo
      shell:
        cmd: 'echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list'

    - name: install nomad
      package:
        name: nomad
        state: present
        update_cache: true






    